myspace_bookmark:
    resource: "@MyspaceBookmarkBundle/Resources/config/routing.yml"
    prefix: /

myspace_bookmark_restfull:
    type: rest
    resource: "@MyspaceBookmarkBundle/Resources/config/routing_restfull.yml"
    prefix: /
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
