myspace_bookmark_homepage:
    path:     /
    defaults: { _controller: MyspaceBookmarkBundle:Default:index }
myspace_bookmark_import:
    path:     /import
    defaults: { _controller: MyspaceBookmarkBundle:Default:import}
myspace_bookmark_category:
    path:     /category/{catid}
    defaults: { _controller: MyspaceBookmarkBundle:Default:category}
myspace_bookmark_bookmark:
    path:     /bookmark/{bookmarkid}
    defaults: { _controller: MyspaceBookmarkBundle:Default:bookmark}
myspace_bookmark_tag:
    path:     /tag/{tagid}
    defaults: { _controller: MyspaceBookmarkBundle:Default:tag}
myspace_bookmark_api_categories_all:
    path:     /api/categories
    defaults: { _controller: MyspaceBookmarkBundle:Category:all, _format: ~}
    requirements:
        _method: GET		