myspace_bookmark_homepage:
    path:     /
    defaults: { _controller: MyspaceBookmarkBundle:Default:index }
myspace_bookmark_import:
    path:     /import
    defaults: { _controller: MyspaceBookmarkBundle:Default:import}	