myspace_bookmark_angurlajs:
    path:     /gl
    defaults: { _controller:MyspaceBookmarkBundle:Default:angularjs}
bookmarks:
    resource: "@MyspaceBookmarkBundle/Controller/"
    type:     annotation
    prefix:   /

