myspace_bookmark_user_restfull_api:
    type: rest
    prefix: /api/v1
    resource: Myspace\BookmarkBundle\Controller\UsersController
    name_prefix: api_1_
    name_prefix: api_v1
myspace_bookmark_category_restfull_api:
    type: rest
    prefix: /api/v1
    resource: Myspace\BookmarkBundle\Controller\CategoryController
    name_prefix: api_1_
myspace_bookmark_bookmark_restfull_api:
    type: rest
    prefix: /api/v1
    resource: Myspace\BookmarkBundle\Controller\BookmarkController
    name_prefix: api_1_	