services:
#    myspace_bookmark.example:
#        class: Myspace\BookmarkBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    myspace_bookmark.string_service:
        class: Myspace\BookmarkBundle\Services\StringService
        autowire: true

    jms_serializer.camel_case_naming_strategy:
        class: 'JMS\Serializer\Naming\IdenticalPropertyNamingStrategy'